// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlACw9WsBIrm-hzw3wp8csc06a6BuPzfc',
    appId: '1:55865567936:web:5234860f26624318275b25',
    messagingSenderId: '55865567936',
    projectId: 'accesorios-para-mascotas-96d2a',
    authDomain: 'accesorios-para-mascotas-96d2a.firebaseapp.com',
    storageBucket: 'accesorios-para-mascotas-96d2a.appspot.com',
    measurementId: 'G-7LMGJ8N7QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxGTsWwxMUajQA_8HzHGn26kYYzWAcxKs',
    appId: '1:55865567936:android:e32564d79ef2e79c275b25',
    messagingSenderId: '55865567936',
    projectId: 'accesorios-para-mascotas-96d2a',
    storageBucket: 'accesorios-para-mascotas-96d2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7vIhkWq_mf90lAnSnw8xB3PpLFEuB6k',
    appId: '1:55865567936:ios:825c21de7a79f465275b25',
    messagingSenderId: '55865567936',
    projectId: 'accesorios-para-mascotas-96d2a',
    storageBucket: 'accesorios-para-mascotas-96d2a.appspot.com',
    iosClientId: '55865567936-bho6gqgkgk7tpv0orpkmfe2qmo2v6l8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.accesoriosParaMascotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7vIhkWq_mf90lAnSnw8xB3PpLFEuB6k',
    appId: '1:55865567936:ios:825c21de7a79f465275b25',
    messagingSenderId: '55865567936',
    projectId: 'accesorios-para-mascotas-96d2a',
    storageBucket: 'accesorios-para-mascotas-96d2a.appspot.com',
    iosClientId: '55865567936-bho6gqgkgk7tpv0orpkmfe2qmo2v6l8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.accesoriosParaMascotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlACw9WsBIrm-hzw3wp8csc06a6BuPzfc',
    appId: '1:55865567936:web:1364eb421d89111a275b25',
    messagingSenderId: '55865567936',
    projectId: 'accesorios-para-mascotas-96d2a',
    authDomain: 'accesorios-para-mascotas-96d2a.firebaseapp.com',
    storageBucket: 'accesorios-para-mascotas-96d2a.appspot.com',
    measurementId: 'G-7N62SVZHHP',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBlACw9WsBIrm-hzw3wp8csc06a6BuPzfc',
    appId: '1:55865567936:web:a3442e21375df1fb275b25',
    messagingSenderId: '55865567936',
    projectId: 'accesorios-para-mascotas-96d2a',
    authDomain: 'accesorios-para-mascotas-96d2a.firebaseapp.com',
    storageBucket: 'accesorios-para-mascotas-96d2a.appspot.com',
    measurementId: 'G-GW9821HQZH',
  );
}
